FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish src/TelegramAutomation.FakeTelegramApi/TelegramAutomation.FakeTelegramApi.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./
USER 64198
EXPOSE 8080
ENTRYPOINT ["dotnet", "TelegramAutomation.FakeTelegramApi.dll"]
